version: '3.8'

services:
  db:
    image: postgres
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

  grammar:
    build: 
      context: ./Grammar
      dockerfile: Dockerfile
    container_name: grammar_check
    ports:
      - "8000:8000"
    volumes:
      - grammar_data:/app
    depends_on:
      - db
    networks:
      - postgres_network

  api:
    build:
      context: ./API/src/MonkeyServer
      dockerfile: Dockerfile  
    container_name: monkey_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file: ".env"
    ports:
      - "8080:8080"
    depends_on:
      - db
      - grammar
    networks:
      - postgres_network

volumes:
  postgres_data:
  grammar_data:

networks:
  postgres_network:
