/*
 * Book API
 *
 * This is a simple server for loading and saving random books
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using MonkeyServer.Attributes;
using Microsoft.AspNetCore.Mvc;
using MonkeyServer.DTOs;
using MonkeyServer.Services;
using Newtonsoft.Json;
using Swashbuckle.AspNetCore.Annotations;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace MonkeyServer.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class BooksApiController : ControllerBase
    {
        private readonly IBookService _bookService;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="bookService"></param>
        public BooksApiController(IBookService bookService)
        {
            _bookService = bookService;
        }

        /// <summary>
        /// Get longest books
        /// </summary>
        /// <response code="200">sucessfully got books by length</response>
        [HttpGet]
        [Route("/v1/books")]
        [Consumes("application/json")]
        [Produces("application/json")]
        [ValidateModelState]
        [SwaggerOperation("BooksGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<BookDTO>), description: "sucessfully got books by length")]
        public virtual IActionResult BooksGet()
        {
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<Object>));
            string exampleJson = null;
            exampleJson = "[ \"\", \"\" ]";

            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<List<object>>(exampleJson)
            : default;            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
